server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielid258/config-repo
          username: danielid258
          password: Daniel@100304
          basedir: E:\configRepository\git # fetch config from git and save to config-server local path

#== uses native config begin ==#

#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native
#== uses native config end ==#

  rabbitmq:
      host: 192.168.42.53
      port: 5672
      username: admin
      password: 123456

#actives /actuator/bus-refresh
#request /actuator/bus-refresh to refresh config dynamic
management:
  endpoints:
    web:
      exposure:
        include: "*"